services:
  - type: web
    name: borders-dynasty
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "node server.js"
    envVars:
      - key: RPC_URL
        sync: false
      - key: PRIVATE_KEY
        sync: false
      - key: ALCHEMY_AUTH_TOKEN
        sync: false
      - key: WEBHOOK_ID
        sync: false
      - key: KING
        sync: false
