services:
  - type: web
    name: borders-dynasty
    env: node
    plan: free
    region: oregon
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: RPC_URL
        fromSecret: RPC_URL
      - key: PRIVATE_KEY
        fromSecret: PRIVATE_KEY
      - key: ETHERSCAN_API_KEY
        fromSecret: ETHERSCAN_API_KEY
      - key: ALCHEMY_API_KEY
        fromSecret: ALCHEMY_API_KEY
      - key: ALCHEMY_APP_ID
        value: "lm9vdq2okew29efg"
